// <copyright file="CardTest.CardsToDeal.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.GameLogicV2
{
    public partial class CardTest {
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CardsToDeal166()
{
    int i;
    i = this.CardsToDeal(1, 994);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CardsToDeal121()
{
    int i;
    i = this.CardsToDeal(11, 1);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CardsToDeal329()
{
    int i;
    i = this.CardsToDeal(1, 1);
    Assert.AreEqual<int>(10, i);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CardsToDealThrowsContractException546()
{
    try
    {
      int i;
      i = this.CardsToDeal(1, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CardsToDealThrowsContractException50()
{
    try
    {
      int i;
      i = this.CardsToDeal(0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
