// <copyright file="CardTest.FromString.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.GameLogicV2
{
    public partial class CardTest {
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void FromString974()
{
    Card card;
    card = this.FromString("card: Clubs;Jack");
    Assert.IsNotNull((object)card);
    Assert.AreEqual<CardValue>(CardValue.Jack, card.Value);
    Assert.AreEqual<Suit>(Suit.Clubs, card.Suit);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void FromStringThrowsContractException257()
{
    try
    {
      Card card;
      card = this.FromString("");
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void FromStringThrowsContractException744()
{
    try
    {
      Card card;
      card = this.FromString((string)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
