// <copyright file="CardTest.CompareTo.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Explorable;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PirateSpades.GameLogicV2
{
    public partial class CardTest {
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CompareTo432()
{
    Card card;
    Card card1;
    int i;
    card = PexInvariant.CreateInstance<Card>();
    PexInvariant.SetField<CardValue>
        ((object)card, "<Value>k__BackingField", CardValue.Two);
    PexInvariant.SetField<Suit>((object)card, "<Suit>k__BackingField", Suit.Spades);
    PexInvariant.CheckInvariant((object)card);
    card1 = PexInvariant.CreateInstance<Card>();
    PexInvariant.SetField<CardValue>
        ((object)card1, "<Value>k__BackingField", CardValue.King);
    PexInvariant.SetField<Suit>((object)card1, "<Suit>k__BackingField", Suit.Spades);
    PexInvariant.CheckInvariant((object)card1);
    i = this.CompareTo(card1, (object)card);
    Assert.AreEqual<int>(1, i);
    Assert.IsNotNull((object)card1);
    Assert.AreEqual<CardValue>(CardValue.King, card1.Value);
    Assert.AreEqual<Suit>(Suit.Spades, card1.Suit);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CompareTo71()
{
    Card card;
    Card card1;
    int i;
    card = PexInvariant.CreateInstance<Card>();
    PexInvariant.SetField<CardValue>
        ((object)card, "<Value>k__BackingField", CardValue.Two);
    PexInvariant.SetField<Suit>((object)card, "<Suit>k__BackingField", Suit.Spades);
    PexInvariant.CheckInvariant((object)card);
    card1 = PexInvariant.CreateInstance<Card>();
    PexInvariant.SetField<CardValue>
        ((object)card1, "<Value>k__BackingField", CardValue.Five);
    PexInvariant.SetField<Suit>
        ((object)card1, "<Suit>k__BackingField", Suit.Diamonds);
    PexInvariant.CheckInvariant((object)card1);
    i = this.CompareTo(card1, (object)card);
    Assert.AreEqual<int>(-1, i);
    Assert.IsNotNull((object)card1);
    Assert.AreEqual<CardValue>(CardValue.Five, card1.Value);
    Assert.AreEqual<Suit>(Suit.Diamonds, card1.Suit);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CompareTo330()
{
    Card card;
    int i;
    card = PexInvariant.CreateInstance<Card>();
    PexInvariant.SetField<CardValue>
        ((object)card, "<Value>k__BackingField", CardValue.Two);
    PexInvariant.SetField<Suit>((object)card, "<Suit>k__BackingField", Suit.Spades);
    PexInvariant.CheckInvariant((object)card);
    i = this.CompareTo(card, (object)card);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)card);
    Assert.AreEqual<CardValue>(CardValue.Two, card.Value);
    Assert.AreEqual<Suit>(Suit.Spades, card.Suit);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CompareTo830()
{
    Card card;
    int i;
    card = PexInvariant.CreateInstance<Card>();
    PexInvariant.SetField<CardValue>
        ((object)card, "<Value>k__BackingField", CardValue.Two);
    PexInvariant.SetField<Suit>((object)card, "<Suit>k__BackingField", Suit.Spades);
    PexInvariant.CheckInvariant((object)card);
    object s0 = new object();
    i = this.CompareTo(card, s0);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)card);
    Assert.AreEqual<CardValue>(CardValue.Two, card.Value);
    Assert.AreEqual<Suit>(Suit.Spades, card.Suit);
}
[TestMethod]
[PexGeneratedBy(typeof(CardTest))]
public void CompareTo344()
{
    Card card;
    int i;
    card = PexInvariant.CreateInstance<Card>();
    PexInvariant.SetField<CardValue>
        ((object)card, "<Value>k__BackingField", CardValue.Two);
    PexInvariant.SetField<Suit>
        ((object)card, "<Suit>k__BackingField", Suit.Diamonds);
    PexInvariant.CheckInvariant((object)card);
    i = this.CompareTo(card, (object)null);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)card);
    Assert.AreEqual<CardValue>(CardValue.Two, card.Value);
    Assert.AreEqual<Suit>(Suit.Diamonds, card.Suit);
}
    }
}
