// <copyright file="CollectionFncTest.PickRandom02.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Misc
{
    public partial class CollectionFncTest {
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
public void PickRandom02794()
{
    List<int> list;
    int i;
    int[] ints = new int[1];
    list = new List<int>((IEnumerable<int>)ints);
    i = this.PickRandom02<int>(list);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PickRandom02ThrowsContractException680()
{
    try
    {
      List<int> list;
      int i;
      int[] ints = new int[0];
      list = new List<int>((IEnumerable<int>)ints);
      i = this.PickRandom02<int>(list);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PickRandom02ThrowsContractException473()
{
    try
    {
      int i;
      i = this.PickRandom02<int>((List<int>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
