// <copyright file="CollectionFncTest.PickRandom01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Misc
{
    public partial class CollectionFncTest {
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
public void PickRandom01794()
{
    int i;
    int[] ints = new int[1];
    i = this.PickRandom01<int>((IEnumerable<int>)ints);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PickRandom01ThrowsContractException272()
{
    try
    {
      int i;
      int[] ints = new int[0];
      i = this.PickRandom01<int>((IEnumerable<int>)ints);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PickRandom01ThrowsContractException398()
{
    try
    {
      int i;
      i = this.PickRandom01<int>((IEnumerable<int>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
public void PickRandom794()
{
    int i;
    int[] ints = new int[1];
    i = this.PickRandom<int>((ICollection<int>)ints);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PickRandomThrowsContractException303()
{
    try
    {
      int i;
      int[] ints = new int[0];
      i = this.PickRandom<int>((ICollection<int>)ints);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(CollectionFncTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PickRandomThrowsContractException320()
{
    try
    {
      int i;
      i = this.PickRandom<int>((ICollection<int>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
