// <copyright file="GameTest.ClearPlayers.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PirateSpades.GameLogicV2
{
    using PirateSpades.GameLogic;

    public partial class GameTest {
[TestMethod]
[PexGeneratedBy(typeof(GameTest))]
public void ClearPlayers273()
{
    Game game;
    game = new Game();
    this.ClearPlayers(game);
    Assert.IsNotNull((object)game);
    Assert.IsNotNull(game.Players);
    Assert.AreEqual<int>(-1, game.CurrentDealer);
    Assert.AreEqual<int>(0, game.CurrentRound);
    Assert.AreEqual<bool>(false, game.Started);
}
    }
}
