// <copyright file="GameTest.AddPlayers.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.GameLogicV2
{
    public partial class GameTest {
[TestMethod]
[PexGeneratedBy(typeof(GameTest))]
public void AddPlayers5()
{
    Game game;
    game = new Game();
    Player[] players = new Player[2];
    this.AddPlayers(game, (IEnumerable<Player>)players);
    Assert.IsNotNull((object)game);
    Assert.IsNotNull(game.Players);
    Assert.AreEqual<int>(-1, game.CurrentDealer);
    Assert.AreEqual<int>(0, game.CurrentRound);
    Assert.AreEqual<bool>(false, game.Started);
}
[TestMethod]
[PexGeneratedBy(typeof(GameTest))]
public void AddPlayers412()
{
    Game game;
    game = new Game();
    Player[] players = new Player[1];
    this.AddPlayers(game, (IEnumerable<Player>)players);
    Assert.IsNotNull((object)game);
    Assert.IsNotNull(game.Players);
    Assert.AreEqual<int>(-1, game.CurrentDealer);
    Assert.AreEqual<int>(0, game.CurrentRound);
    Assert.AreEqual<bool>(false, game.Started);
}
[TestMethod]
[PexGeneratedBy(typeof(GameTest))]
public void AddPlayers986()
{
    Game game;
    game = new Game();
    Player[] players = new Player[0];
    this.AddPlayers(game, (IEnumerable<Player>)players);
    Assert.IsNotNull((object)game);
    Assert.IsNotNull(game.Players);
    Assert.AreEqual<int>(-1, game.CurrentDealer);
    Assert.AreEqual<int>(0, game.CurrentRound);
    Assert.AreEqual<bool>(false, game.Started);
}
[TestMethod]
[PexGeneratedBy(typeof(GameTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AddPlayersThrowsContractException444()
{
    try
    {
      Game game;
      game = new Game();
      this.AddPlayers(game, (IEnumerable<Player>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GameTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AddPlayerThrowsContractException74()
{
    try
    {
      Game game;
      game = new Game();
      this.AddPlayer(game, (Player)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
