// <copyright file="ImmutableOrderedDictionaryTKeyTValueTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Specialized;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Misc
{
    public partial class ImmutableOrderedDictionaryTKeyTValueTest {
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
public void Constructor629()
{
    OrderedDictionary<int, int> orderedDictionary;
    ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    immutableOrderedDictionary = this.Constructor<int, int>(orderedDictionary);
    Assert.IsNotNull((object)immutableOrderedDictionary);
    Assert.AreEqual<bool>
        (false, ((OrderedDictionary)immutableOrderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException783()
{
    try
    {
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      immutableOrderedDictionary =
        this.Constructor<int, int>((OrderedDictionary<int, int>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
