// <copyright file="ImmutableOrderedDictionaryTKeyTValueTest.ItemGet01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Engine.Exceptions;
using System.Collections.Specialized;

namespace PirateSpades.Misc
{
    public partial class ImmutableOrderedDictionaryTKeyTValueTest {
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGet01ThrowsContractException961()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      int i;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi, -2147482870);
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      i = this.ItemGet01<int, int>(immutableOrderedDictionary, 778);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGet01ThrowsContractException636()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      int i;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi, 183);
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      i = this.ItemGet01<int, int>(immutableOrderedDictionary, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGet01ThrowsContractException194()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      int i;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi, 7471516);
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      i = this.ItemGet01<int, int>(immutableOrderedDictionary, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
public void ItemGet01549()
{
    OrderedDictionary<int, int> orderedDictionary;
    ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
    int i;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    immutableOrderedDictionary =
      new ImmutableOrderedDictionary<int, int>(orderedDictionary);
    i = this.ItemGet01<int, int>(immutableOrderedDictionary, 0);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)immutableOrderedDictionary);
    Assert.AreEqual<bool>
        (false, ((OrderedDictionary)immutableOrderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGetThrowsContractException422()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      object o;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi, 629);
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      object boxi2 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi2, -2147483019);
      o = this.ItemGet<int, int>(immutableOrderedDictionary, boxi2);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGetThrowsContractException94()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      object o;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi, 13);
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      object boxi2 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi2, 198150);
      o = this.ItemGet<int, int>(immutableOrderedDictionary, boxi2);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGetThrowsContractException676()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      object o;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      object boxi2 = (object)(default(int));
      PexSafeHelpers.AssignBoxedValue<int>(boxi2, 48);
      o = this.ItemGet<int, int>(immutableOrderedDictionary, boxi2);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
public void ItemGet549()
{
    OrderedDictionary<int, int> orderedDictionary;
    ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
    object o;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    immutableOrderedDictionary =
      new ImmutableOrderedDictionary<int, int>(orderedDictionary);
    object boxi2 = (object)(default(int));
    o = this.ItemGet<int, int>(immutableOrderedDictionary, boxi2);
    Assert.IsNotNull((object)immutableOrderedDictionary);
    Assert.AreEqual<bool>
        (false, ((OrderedDictionary)immutableOrderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGetThrowsContractException527()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      object o;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      object s0 = new object();
      o = this.ItemGet<int, int>(immutableOrderedDictionary, s0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ImmutableOrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ItemGetThrowsContractException507()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      ImmutableOrderedDictionary<int, int> immutableOrderedDictionary;
      object o;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      immutableOrderedDictionary =
        new ImmutableOrderedDictionary<int, int>(orderedDictionary);
      o = this.ItemGet<int, int>(immutableOrderedDictionary, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
