// <copyright file="OrderedDictionaryTKeyTValueTest.Add01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Specialized;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Misc
{
    public partial class OrderedDictionaryTKeyTValueTest {
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
public void Add01720()
{
    OrderedDictionary<int, int> orderedDictionary;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi, 25345888);
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    this.Add01<int, int>(orderedDictionary, 2117075160, 0);
    Assert.IsNotNull((object)orderedDictionary);
    Assert.AreEqual<bool>(false, ((OrderedDictionary)orderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Add01ThrowsContractException923()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Add01<int, int>(orderedDictionary, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
public void Add628()
{
    OrderedDictionary<int, int> orderedDictionary;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi, 923304960);
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    object boxi2 = (object)(default(int));
    object boxi3 = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi2, -1224178688);
    this.Add<int, int>(orderedDictionary, boxi2, boxi3);
    Assert.IsNotNull((object)orderedDictionary);
    Assert.AreEqual<bool>(false, ((OrderedDictionary)orderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AddThrowsContractException443()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      object boxi2 = (object)(default(int));
      object boxi3 = (object)(default(int));
      this.Add<int, int>(orderedDictionary, boxi2, boxi3);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AddThrowsContractException229()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      object boxi2 = (object)(default(int));
      this.Add<int, int>(orderedDictionary, boxi2, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AddThrowsContractException783()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      object boxi2 = (object)(default(int));
      object s0 = new object();
      this.Add<int, int>(orderedDictionary, boxi2, s0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AddThrowsContractException756()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      object s0 = new object();
      this.Add<int, int>(orderedDictionary, s0, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AddThrowsContractException315()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Add<int, int>(orderedDictionary, (object)null, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
