// <copyright file="OrderedDictionaryTKeyTValueTest.Remove01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Specialized;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Misc
{
    public partial class OrderedDictionaryTKeyTValueTest {
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
public void Remove01732()
{
    OrderedDictionary<int, int> orderedDictionary;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    this.Remove01<int, int>(orderedDictionary, 0);
    Assert.IsNotNull((object)orderedDictionary);
    Assert.AreEqual<bool>(false, ((OrderedDictionary)orderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
public void Remove732()
{
    OrderedDictionary<int, int> orderedDictionary;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    object boxi2 = (object)(default(int));
    this.Remove<int, int>(orderedDictionary, boxi2);
    Assert.IsNotNull((object)orderedDictionary);
    Assert.AreEqual<bool>(false, ((OrderedDictionary)orderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void RemoveThrowsContractException609()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Remove<int, int>(orderedDictionary, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
