// <copyright file="OrderedDictionaryTKeyTValueTest.Insert01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Specialized;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Misc
{
    public partial class OrderedDictionaryTKeyTValueTest {
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
public void Insert01202()
{
    OrderedDictionary<int, int> orderedDictionary;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi, -2147483616);
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    this.Insert01<int, int>(orderedDictionary, 0, 32, 0);
    Assert.IsNotNull((object)orderedDictionary);
    Assert.AreEqual<bool>(false, ((OrderedDictionary)orderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Insert01ThrowsContractException877()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Insert01<int, int>(orderedDictionary, int.MinValue, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Insert01ThrowsContractException181()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Insert01<int, int>(orderedDictionary, 0, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
public void Insert96()
{
    OrderedDictionary<int, int> orderedDictionary;
    object boxi = (object)(default(int));
    object boxi1 = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi, 767);
    orderedDictionary = new OrderedDictionary<int, int>();
    orderedDictionary[boxi] = boxi1;
    object boxi2 = (object)(default(int));
    object boxi3 = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi2, 656413596);
    this.Insert<int, int>(orderedDictionary, 0, boxi2, boxi3);
    Assert.IsNotNull((object)orderedDictionary);
    Assert.AreEqual<bool>(false, ((OrderedDictionary)orderedDictionary).IsReadOnly);
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void InsertThrowsContractException850()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      object boxi2 = (object)(default(int));
      object boxi3 = (object)(default(int));
      this.Insert<int, int>(orderedDictionary, 0, boxi2, boxi3);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void InsertThrowsContractException754()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Insert<int, int>
          (orderedDictionary, int.MinValue, (object)null, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void InsertThrowsContractException144()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      object boxi2 = (object)(default(int));
      this.Insert<int, int>(orderedDictionary, 0, boxi2, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void InsertThrowsContractException550()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Insert<int, int>(orderedDictionary, 512, (object)null, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OrderedDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void InsertThrowsContractException267()
{
    try
    {
      OrderedDictionary<int, int> orderedDictionary;
      object boxi = (object)(default(int));
      object boxi1 = (object)(default(int));
      orderedDictionary = new OrderedDictionary<int, int>();
      orderedDictionary[boxi] = boxi1;
      this.Insert<int, int>(orderedDictionary, 0, (object)null, (object)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
