// <copyright file="PirateScannerTest.ScanForIps.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Net;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateScannerTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
public void ScanForIps908()
{
    PirateScanner pirateScanner;
    IList<IPAddress> iList;
    pirateScanner = new PirateScanner();
    iList = this.ScanForIps(pirateScanner, 0, 0, 0);
    Assert.IsNotNull((object)iList);
    Assert.IsNotNull((object)pirateScanner);
    Assert.AreEqual<int>(0, pirateScanner.IpCount);
    Assert.AreEqual<int>(0, pirateScanner.IpsChecked);
    Assert.AreEqual<bool>(false, pirateScanner.CheckRunning);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ScanForIpThrowsContractException214()
{
    try
    {
      PirateScanner pirateScanner;
      IPAddress iPAddress;
      pirateScanner = new PirateScanner();
      iPAddress = this.ScanForIp(pirateScanner, 65536);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ScanForIpThrowsContractException828()
{
    try
    {
      PirateScanner pirateScanner;
      IPAddress iPAddress;
      pirateScanner = new PirateScanner();
      iPAddress = this.ScanForIp(pirateScanner, int.MinValue);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
