// <copyright file="PirateScannerTest.CheckIp.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Net;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateScannerTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CheckIpThrowsContractException205()
{
    try
    {
      IPAddress iPAddress;
      bool b;
      byte[] bs = new byte[16];
      bs[0] = (byte)1;
      iPAddress = new IPAddress(bs);
      iPAddress.ScopeId = 1L;
      b = this.CheckIp(iPAddress, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CheckIpThrowsContractException472()
{
    try
    {
      IPAddress iPAddress;
      bool b;
      byte[] bs = new byte[16];
      iPAddress = new IPAddress(bs);
      iPAddress.ScopeId = 0L;
      b = this.CheckIp(iPAddress, 65536, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CheckIpThrowsContractException740()
{
    try
    {
      IPAddress iPAddress;
      bool b;
      byte[] bs = new byte[16];
      iPAddress = new IPAddress(bs);
      iPAddress.ScopeId = 0L;
      b = this.CheckIp(iPAddress, int.MinValue, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CheckIpThrowsContractException353()
{
    try
    {
      IPAddress iPAddress;
      bool b;
      byte[] bs = new byte[16];
      iPAddress = new IPAddress(bs);
      iPAddress.ScopeId = 1L;
      b = this.CheckIp(iPAddress, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CheckIpThrowsContractException15()
{
    try
    {
      IPAddress iPAddress;
      bool b;
      byte[] bs = new byte[16];
      iPAddress = new IPAddress(bs);
      iPAddress.ScopeId = 0L;
      b = this.CheckIp(iPAddress, 0, int.MinValue);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CheckIpThrowsContractException653()
{
    try
    {
      IPAddress iPAddress;
      bool b;
      byte[] bs = new byte[16];
      iPAddress = new IPAddress(bs);
      iPAddress.ScopeId = 0L;
      b = this.CheckIp(iPAddress, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CheckIpThrowsContractException522()
{
    try
    {
      bool b;
      b = this.CheckIp((IPAddress)null, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
