// <copyright file="PirateMessageTest.GetPlayerTricks.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateMessageTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks535()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "player_tricks: \u0100;0\0");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks02()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "player_tricks: \u0100;0");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(1, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks77()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "player_tricks: \u0100\u0100");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks268()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "player_tricks: \u0100\0");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks741()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "player_tricks: \u0100");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks800()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, "player_tricks: \0");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks01()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, "player_tricks: ");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks698()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, new string('\0', 15));
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetPlayerTricks828()
{
    PirateMessage pirateMessage;
    Dictionary<string, int> dictionary;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, "");
    dictionary = this.GetPlayerTricks(pirateMessage);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void GetPlayerTricksThrowsContractException375()
{
    try
    {
      Dictionary<string, int> dictionary;
      dictionary = this.GetPlayerTricks((PirateMessage)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
