// <copyright file="PirateMessageTest.Constructor01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateMessageTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void Constructor01816()
{
    PirateMessage pirateMessage;
    pirateMessage = this.Constructor01(PirateMessageHead.Fail, "");
    Assert.IsNotNull((object)pirateMessage);
    Assert.AreEqual<PirateMessageHead>(PirateMessageHead.Fail, pirateMessage.Head);
    Assert.AreEqual<string>("", pirateMessage.Body);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException8()
{
    try
    {
      PirateMessage pirateMessage;
      pirateMessage = this.Constructor01(PirateMessageHead.Fail, (string)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void Constructor991()
{
    PirateMessage pirateMessage;
    pirateMessage = this.Constructor("", "");
    Assert.IsNotNull((object)pirateMessage);
    Assert.AreEqual<PirateMessageHead>(PirateMessageHead.Fail, pirateMessage.Head);
    Assert.AreEqual<string>("", pirateMessage.Body);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException653()
{
    try
    {
      PirateMessage pirateMessage;
      pirateMessage = this.Constructor("", (string)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException614()
{
    try
    {
      PirateMessage pirateMessage;
      pirateMessage = this.Constructor((string)null, (string)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
