// <copyright file="PlayerTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PirateSpades.GameLogicV2
{
    public partial class PlayerTest {
[TestMethod]
[PexGeneratedBy(typeof(PlayerTest))]
public void Constructor844()
{
    Player player;
    player = this.Constructor((string)null);
    Assert.IsNotNull((object)player);
    Assert.IsNull(player.Game);
    Assert.AreEqual<string>((string)null, player.Name);
    Assert.AreEqual<int>(0, player.Bet);
    Assert.AreEqual<bool>(false, player.IsDealer);
    Assert.IsNull(player.CardToPlay);
    Assert.IsNotNull(player.Hand);
}
    }
}
