// <copyright file="RoundTest.RoundsPossible.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.GameLogicV2
{
    public partial class RoundTest {
[TestMethod]
[PexGeneratedBy(typeof(RoundTest))]
public void RoundsPossible519()
{
    int i;
    i = this.RoundsPossible(66);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(RoundTest))]
public void RoundsPossible717()
{
    int i;
    i = this.RoundsPossible(1);
    Assert.AreEqual<int>(20, i);
}
[TestMethod]
[PexGeneratedBy(typeof(RoundTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void RoundsPossibleThrowsContractException938()
{
    try
    {
      int i;
      i = this.RoundsPossible(0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
