// <copyright file="TrickTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PirateSpades.GameLogicV2
{
    using PirateSpades.GameLogic;

    public partial class TrickTest {
[TestMethod]
[PexGeneratedBy(typeof(TrickTest))]
public void Constructor692()
{
    Trick trick;
    trick = this.Constructor();
    Assert.IsNotNull((object)trick);
    Assert.IsNotNull(trick.Pile);
    Assert.AreEqual<bool>(false, trick.Pile.IsReadOnly);
    Assert.IsNull(trick.FirstCard);
}
    }
}
