// <copyright file="PirateMessageTest.GetWinner.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateMessageTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetWinner838()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "winning_player: 00\u00fb");
    s = this.GetWinner(pirateMessage);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetWinner424()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "winning_player: 0\u00f6\u803c");
    s = this.GetWinner(pirateMessage);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetWinner496()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "winning_player: 0\u00fb");
    s = this.GetWinner(pirateMessage);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetWinner535()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage =
      new PirateMessage(PirateMessageHead.Fail, "winning_player: 00000000");
    s = this.GetWinner(pirateMessage);
    Assert.AreEqual<string>("00000000", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetWinner103()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, "winning_player: a0");
    s = this.GetWinner(pirateMessage);
    Assert.AreEqual<string>("a0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void GetWinnerThrowsContractException101()
{
    try
    {
      PirateMessage pirateMessage;
      string s;
      pirateMessage = new PirateMessage(PirateMessageHead.Fail, "");
      s = this.GetWinner(pirateMessage);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void GetWinnerThrowsContractException738()
{
    try
    {
      string s;
      s = this.GetWinner((PirateMessage)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
