// <copyright file="PirateMessageTest.GetDealer.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateMessageTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetDealer695()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, "dealer: 00000000");
    s = this.GetDealer(pirateMessage);
    Assert.AreEqual<string>("00000000", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetDealer409()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, "dealer: a");
    s = this.GetDealer(pirateMessage);
    Assert.AreEqual<string>("a", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void GetDealer224()
{
    PirateMessage pirateMessage;
    string s;
    pirateMessage = new PirateMessage(PirateMessageHead.Fail, "dealer: 0");
    s = this.GetDealer(pirateMessage);
    Assert.AreEqual<string>("0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void GetDealerThrowsContractException313()
{
    try
    {
      PirateMessage pirateMessage;
      string s;
      pirateMessage = new PirateMessage(PirateMessageHead.Fail, "");
      s = this.GetDealer(pirateMessage);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void GetDealerThrowsContractException875()
{
    try
    {
      string s;
      s = this.GetDealer((PirateMessage)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
