// <copyright file="PirateMessageTest.AppendBody.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateMessageTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void AppendBody604()
{
    string s;
    string[] ss = new string[0];
    s = this.AppendBody("\0", ss);
    Assert.AreEqual<string>("\0\n", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void AppendBody136()
{
    string s;
    string[] ss = new string[2];
    s = this.AppendBody("", ss);
    Assert.AreEqual<string>("\n", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void AppendBody214()
{
    string s;
    string[] ss = new string[0];
    s = this.AppendBody("", ss);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AppendBodyThrowsContractException943()
{
    try
    {
      string s;
      s = this.AppendBody("", (string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AppendBodyThrowsContractException475()
{
    try
    {
      string s;
      s = this.AppendBody((string)null, (string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
