// <copyright file="PirateMessageTest.ConstructBody01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace PirateSpades.Network
{
    public partial class PirateMessageTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void ConstructBody0190()
{
    string s;
    string[] ss = new string[2];
    s = this.ConstructBody01((IEnumerable<string>)ss);
    Assert.AreEqual<string>("\n", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void ConstructBody01480()
{
    string s;
    string[] ss = new string[1];
    s = this.ConstructBody01((IEnumerable<string>)ss);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void ConstructBody01282()
{
    string s;
    string[] ss = new string[0];
    s = this.ConstructBody01((IEnumerable<string>)ss);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructBody01ThrowsContractException613()
{
    try
    {
      string s;
      s = this.ConstructBody01((IEnumerable<string>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void ConstructBody90()
{
    string s;
    string[] ss = new string[2];
    s = this.ConstructBody(ss);
    Assert.AreEqual<string>("\n", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
public void ConstructBody282()
{
    string s;
    string[] ss = new string[0];
    s = this.ConstructBody(ss);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(PirateMessageTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructBodyThrowsContractException961()
{
    try
    {
      string s;
      s = this.ConstructBody((string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
