// <copyright file="PirateScannerTest.ScanForGames.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PirateSpades.Network
{
    public partial class PirateScannerTest {
[TestMethod]
[PexGeneratedBy(typeof(PirateScannerTest))]
public void ScanForGames83()
{
    PirateScanner pirateScanner;
    IList<PirateScanner.GameInfo> iList;
    pirateScanner = new PirateScanner();
    iList = this.ScanForGames(pirateScanner, 0, 0);
    Assert.IsNotNull((object)iList);
    Assert.IsNotNull((object)pirateScanner);
    Assert.AreEqual<bool>(false, pirateScanner.CheckRunning);
}
    }
}
